// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DataCatalogSpec defines the desired state of DataCatalog.
//
// Contains information about a data catalog in an Amazon Web Services account.
//
// In the Athena console, data catalogs are listed as "data sources" on the
// Data sources page under the Data source name column.
type DataCatalogSpec struct {

	// A description of the data catalog to be created.
	Description *string `json:"description,omitempty"`
	// The name of the data catalog to create. The catalog name must be unique for
	// the Amazon Web Services account and can use a maximum of 127 alphanumeric,
	// underscore, at sign, or hyphen characters. The remainder of the length constraint
	// of 256 is reserved for use by Athena.
	//
	// For FEDERATED type the catalog name has following considerations and limits:
	//
	//   - The catalog name allows special characters such as _ , @ , \ , - . These
	//     characters are replaced with a hyphen (-) when creating the CFN Stack
	//     Name and with an underscore (_) when creating the Lambda Function and
	//     Glue Connection Name.
	//
	//   - The catalog name has a theoretical limit of 128 characters. However,
	//     since we use it to create other resources that allow less characters and
	//     we prepend a prefix to it, the actual catalog name limit for FEDERATED
	//     catalog is 64 - 23 = 41 characters.
	//
	// Regex Pattern: `^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// Specifies the Lambda function or functions to use for creating the data catalog.
	// This is a mapping whose values depend on the catalog type.
	//
	//   - For the HIVE data catalog type, use the following syntax. The metadata-function
	//     parameter is required. The sdk-version parameter is optional and defaults
	//     to the currently supported version. metadata-function=lambda_arn, sdk-version=version_number
	//
	//   - For the LAMBDA data catalog type, use one of the following sets of required
	//     parameters, but not both. If you have one Lambda function that processes
	//     metadata and another for reading the actual data, use the following syntax.
	//     Both parameters are required. metadata-function=lambda_arn, record-function=lambda_arn
	//     If you have a composite Lambda function that processes both metadata and
	//     data, use the following syntax to specify your Lambda function. function=lambda_arn
	//
	//   - The GLUE type takes a catalog ID parameter and is required. The catalog_id
	//     is the account ID of the Amazon Web Services account to which the Glue
	//     Data Catalog belongs. catalog-id=catalog_id The GLUE data catalog type
	//     also applies to the default AwsDataCatalog that already exists in your
	//     account, of which you can have only one and cannot modify.
	//
	//   - The FEDERATED data catalog type uses one of the following parameters,
	//     but not both. Use connection-arn for an existing Glue connection. Use
	//     connection-type and connection-properties to specify the configuration
	//     setting for a new connection. connection-arn: lambda-role-arn (optional):
	//     The execution role to use for the Lambda function. If not provided, one
	//     is created. connection-type:MYSQL|REDSHIFT|...., connection-properties:""
	//     For , use escaped JSON text, as in the following example. "{\"spill_bucket\":\"my_spill\",\"spill_prefix\":\"athena-spill\",\"host\":\"abc12345.snowflakecomputing.com\",\"port\":\"1234\",\"warehouse\":\"DEV_WH\",\"database\":\"TEST\",\"schema\":\"PUBLIC\",\"SecretArn\":\"arn:aws:secretsmanager:ap-south-1:111122223333:secret:snowflake-XHb67j\"}"
	Parameters map[string]*string `json:"parameters,omitempty"`
	// A list of comma separated tags to add to the data catalog that is created.
	// All the resources that are created by the CreateDataCatalog API operation
	// with FEDERATED type will have the tag federated_athena_datacatalog="true".
	// This includes the CFN Stack, Glue Connection, Athena DataCatalog, and all
	// the resources created as part of the CFN Stack (Lambda Function, IAM policies/roles).
	Tags []*Tag `json:"tags,omitempty"`
	// The type of data catalog to create: LAMBDA for a federated catalog, GLUE
	// for an Glue Data Catalog, and HIVE for an external Apache Hive metastore.
	// FEDERATED is a federated catalog for which Athena creates the connection
	// and the Lambda function for you based on the parameters that you pass.
	//
	// For FEDERATED type, we do not support IAM identity center.
	// +kubebuilder:validation:Required
	Type *string `json:"type,omitempty"`
}

// DataCatalogStatus defines the observed state of DataCatalog
type DataCatalogStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The type of connection for a FEDERATED data catalog (for example, REDSHIFT,
	// MYSQL, or SQLSERVER). For information about individual connectors, see Available
	// data source connectors (https://docs.aws.amazon.com/athena/latest/ug/connectors-available.html).
	// +kubebuilder:validation:Optional
	ConnectionType *string `json:"connectionType,omitempty"`
	// Text of the error that occurred during data catalog creation or deletion.
	// +kubebuilder:validation:Optional
	Error *string `json:"error,omitempty"`
	// The status of the creation or deletion of the data catalog.
	//
	//    * The LAMBDA, GLUE, and HIVE data catalog types are created synchronously.
	//    Their status is either CREATE_COMPLETE or CREATE_FAILED.
	//
	//    * The FEDERATED data catalog type is created asynchronously.
	//
	// Data catalog creation status:
	//
	//    * CREATE_IN_PROGRESS: Federated data catalog creation in progress.
	//
	//    * CREATE_COMPLETE: Data catalog creation complete.
	//
	//    * CREATE_FAILED: Data catalog could not be created.
	//
	//    * CREATE_FAILED_CLEANUP_IN_PROGRESS: Federated data catalog creation failed
	//    and is being removed.
	//
	//    * CREATE_FAILED_CLEANUP_COMPLETE: Federated data catalog creation failed
	//    and was removed.
	//
	//    * CREATE_FAILED_CLEANUP_FAILED: Federated data catalog creation failed
	//    but could not be removed.
	//
	// Data catalog deletion status:
	//
	//    * DELETE_IN_PROGRESS: Federated data catalog deletion in progress.
	//
	//    * DELETE_COMPLETE: Federated data catalog deleted.
	//
	//    * DELETE_FAILED: Federated data catalog could not be deleted.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
}

// DataCatalog is the Schema for the DataCatalogs API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type DataCatalog struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DataCatalogSpec   `json:"spec,omitempty"`
	Status            DataCatalogStatus `json:"status,omitempty"`
}

// DataCatalogList contains a list of DataCatalog
// +kubebuilder:object:root=true
type DataCatalogList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DataCatalog `json:"items"`
}

func init() {
	SchemeBuilder.Register(&DataCatalog{}, &DataCatalogList{})
}
