// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AuthenticationType string

const (
	AuthenticationType_DIRECTORY_IDENTITY AuthenticationType = "DIRECTORY_IDENTITY"
)

type CalculationExecutionState string

const (
	CalculationExecutionState_CANCELED  CalculationExecutionState = "CANCELED"
	CalculationExecutionState_CANCELING CalculationExecutionState = "CANCELING"
	CalculationExecutionState_COMPLETED CalculationExecutionState = "COMPLETED"
	CalculationExecutionState_CREATED   CalculationExecutionState = "CREATED"
	CalculationExecutionState_CREATING  CalculationExecutionState = "CREATING"
	CalculationExecutionState_FAILED    CalculationExecutionState = "FAILED"
	CalculationExecutionState_QUEUED    CalculationExecutionState = "QUEUED"
	CalculationExecutionState_RUNNING   CalculationExecutionState = "RUNNING"
)

type CapacityAllocationStatus string

const (
	CapacityAllocationStatus_FAILED    CapacityAllocationStatus = "FAILED"
	CapacityAllocationStatus_PENDING   CapacityAllocationStatus = "PENDING"
	CapacityAllocationStatus_SUCCEEDED CapacityAllocationStatus = "SUCCEEDED"
)

type CapacityReservationStatus string

const (
	CapacityReservationStatus_ACTIVE         CapacityReservationStatus = "ACTIVE"
	CapacityReservationStatus_CANCELLED      CapacityReservationStatus = "CANCELLED"
	CapacityReservationStatus_CANCELLING     CapacityReservationStatus = "CANCELLING"
	CapacityReservationStatus_FAILED         CapacityReservationStatus = "FAILED"
	CapacityReservationStatus_PENDING        CapacityReservationStatus = "PENDING"
	CapacityReservationStatus_UPDATE_PENDING CapacityReservationStatus = "UPDATE_PENDING"
)

type ColumnNullable string

const (
	ColumnNullable_NOT_NULL ColumnNullable = "NOT_NULL"
	ColumnNullable_NULLABLE ColumnNullable = "NULLABLE"
	ColumnNullable_UNKNOWN  ColumnNullable = "UNKNOWN"
)

type ConnectionType string

const (
	ConnectionType_BIGQUERY           ConnectionType = "BIGQUERY"
	ConnectionType_CMDB               ConnectionType = "CMDB"
	ConnectionType_DATALAKEGEN2       ConnectionType = "DATALAKEGEN2"
	ConnectionType_DB2                ConnectionType = "DB2"
	ConnectionType_DB2AS400           ConnectionType = "DB2AS400"
	ConnectionType_DOCUMENTDB         ConnectionType = "DOCUMENTDB"
	ConnectionType_DYNAMODB           ConnectionType = "DYNAMODB"
	ConnectionType_GOOGLECLOUDSTORAGE ConnectionType = "GOOGLECLOUDSTORAGE"
	ConnectionType_HBASE              ConnectionType = "HBASE"
	ConnectionType_MYSQL              ConnectionType = "MYSQL"
	ConnectionType_OPENSEARCH         ConnectionType = "OPENSEARCH"
	ConnectionType_ORACLE             ConnectionType = "ORACLE"
	ConnectionType_POSTGRESQL         ConnectionType = "POSTGRESQL"
	ConnectionType_REDSHIFT           ConnectionType = "REDSHIFT"
	ConnectionType_SAPHANA            ConnectionType = "SAPHANA"
	ConnectionType_SNOWFLAKE          ConnectionType = "SNOWFLAKE"
	ConnectionType_SQLSERVER          ConnectionType = "SQLSERVER"
	ConnectionType_SYNAPSE            ConnectionType = "SYNAPSE"
	ConnectionType_TIMESTREAM         ConnectionType = "TIMESTREAM"
	ConnectionType_TPCDS              ConnectionType = "TPCDS"
)

type DataCatalogStatus_SDK string

const (
	DataCatalogStatus_SDK_CREATE_COMPLETE                   DataCatalogStatus_SDK = "CREATE_COMPLETE"
	DataCatalogStatus_SDK_CREATE_FAILED                     DataCatalogStatus_SDK = "CREATE_FAILED"
	DataCatalogStatus_SDK_CREATE_FAILED_CLEANUP_COMPLETE    DataCatalogStatus_SDK = "CREATE_FAILED_CLEANUP_COMPLETE"
	DataCatalogStatus_SDK_CREATE_FAILED_CLEANUP_FAILED      DataCatalogStatus_SDK = "CREATE_FAILED_CLEANUP_FAILED"
	DataCatalogStatus_SDK_CREATE_FAILED_CLEANUP_IN_PROGRESS DataCatalogStatus_SDK = "CREATE_FAILED_CLEANUP_IN_PROGRESS"
	DataCatalogStatus_SDK_CREATE_IN_PROGRESS                DataCatalogStatus_SDK = "CREATE_IN_PROGRESS"
	DataCatalogStatus_SDK_DELETE_COMPLETE                   DataCatalogStatus_SDK = "DELETE_COMPLETE"
	DataCatalogStatus_SDK_DELETE_FAILED                     DataCatalogStatus_SDK = "DELETE_FAILED"
	DataCatalogStatus_SDK_DELETE_IN_PROGRESS                DataCatalogStatus_SDK = "DELETE_IN_PROGRESS"
)

type DataCatalogType string

const (
	DataCatalogType_FEDERATED DataCatalogType = "FEDERATED"
	DataCatalogType_GLUE      DataCatalogType = "GLUE"
	DataCatalogType_HIVE      DataCatalogType = "HIVE"
	DataCatalogType_LAMBDA    DataCatalogType = "LAMBDA"
)

type EncryptionOption string

const (
	EncryptionOption_CSE_KMS EncryptionOption = "CSE_KMS"
	EncryptionOption_SSE_KMS EncryptionOption = "SSE_KMS"
	EncryptionOption_SSE_S3  EncryptionOption = "SSE_S3"
)

type ExecutorState string

const (
	ExecutorState_CREATED     ExecutorState = "CREATED"
	ExecutorState_CREATING    ExecutorState = "CREATING"
	ExecutorState_FAILED      ExecutorState = "FAILED"
	ExecutorState_REGISTERED  ExecutorState = "REGISTERED"
	ExecutorState_TERMINATED  ExecutorState = "TERMINATED"
	ExecutorState_TERMINATING ExecutorState = "TERMINATING"
)

type ExecutorType string

const (
	ExecutorType_COORDINATOR ExecutorType = "COORDINATOR"
	ExecutorType_GATEWAY     ExecutorType = "GATEWAY"
	ExecutorType_WORKER      ExecutorType = "WORKER"
)

type NotebookType string

const (
	NotebookType_IPYNB NotebookType = "IPYNB"
)

type QueryExecutionState string

const (
	QueryExecutionState_CANCELLED QueryExecutionState = "CANCELLED"
	QueryExecutionState_FAILED    QueryExecutionState = "FAILED"
	QueryExecutionState_QUEUED    QueryExecutionState = "QUEUED"
	QueryExecutionState_RUNNING   QueryExecutionState = "RUNNING"
	QueryExecutionState_SUCCEEDED QueryExecutionState = "SUCCEEDED"
)

type QueryResultType string

const (
	QueryResultType_DATA_MANIFEST QueryResultType = "DATA_MANIFEST"
	QueryResultType_DATA_ROWS     QueryResultType = "DATA_ROWS"
)

type S3ACLOption string

const (
	S3ACLOption_BUCKET_OWNER_FULL_CONTROL S3ACLOption = "BUCKET_OWNER_FULL_CONTROL"
)

type SessionState string

const (
	SessionState_BUSY        SessionState = "BUSY"
	SessionState_CREATED     SessionState = "CREATED"
	SessionState_CREATING    SessionState = "CREATING"
	SessionState_DEGRADED    SessionState = "DEGRADED"
	SessionState_FAILED      SessionState = "FAILED"
	SessionState_IDLE        SessionState = "IDLE"
	SessionState_TERMINATED  SessionState = "TERMINATED"
	SessionState_TERMINATING SessionState = "TERMINATING"
)

type StatementType string

const (
	StatementType_DDL     StatementType = "DDL"
	StatementType_DML     StatementType = "DML"
	StatementType_UTILITY StatementType = "UTILITY"
)

type ThrottleReason string

const (
	ThrottleReason_CONCURRENT_QUERY_LIMIT_EXCEEDED ThrottleReason = "CONCURRENT_QUERY_LIMIT_EXCEEDED"
)

type WorkGroupState string

const (
	WorkGroupState_DISABLED WorkGroupState = "DISABLED"
	WorkGroupState_ENABLED  WorkGroupState = "ENABLED"
)
